config/routes.rb
Doomhub::Application.routes.draw do

  root :to => 'news#index'

  get "/p/:id/m" => redirect("/p/%{id}#maps")
  get "/p/:project_id/m/:id/f" => redirect("/p/%{project_id}/m/%{id}#files")
  get "/p/:project_id/m/:id/i" => redirect("/p/%{project_id}/m/%{id}#images")

  resources :projects, :path => '/p' do
    resources :file_links, path: '/l', except: [:index]
    resources :comments, :path => '/c', except: [:edit]
    resources :resources, :path => '/r', only: [:new, :index]
    resources :maps, :path => '/m', :except => [:index] do
      resources :uploads, :path => '/f', :except => [:index] do
        member { get :download }
      end
      resources :map_images, :path => '/i', :except => [:index] do
        member { get :auth_url }
      end
      resources :file_links, path: '/l', except: [:index]
      resources :resources, :path => '/r', only: [:new, :index]
    end
  end

  resources :news, :path => '/n'

  resources :users, :path => '/u', :only => [:show, :index] do
    resources :projects, :path => '/p'
  end

  devise_for :user, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "new",
    :registration => 'registration'
  }

end

app/models/map.rb
class Map < ActiveRecord::Base

  extend FriendlyId

  acts_as_paranoid

#========
#= ASSOC
#======

  belongs_to :authorable, polymorphic: true
  belongs_to :project

  has_many :comments, as: :commentable
  has_many :map_images
  has_many :uploads
  has_many :file_links, as: :file_linkable

#==============
#= FRIENDLY_ID
#============

  friendly_id :name, :use => [:slugged, :history]

#==============
#= VALIDATIONS
#============

  validates :name, :presence => true
  validate :has_5_uploads_max
  validate :user_can_map

#============
#= CALLBACKS
#==========

  before_save :get_default_lumpname, if: ->(m) {m.lump.nil?}

  def get_default_lumpname
    self.lump = project.game.default_lumpname
  end

#==========
#= METHODS
#========

private

  def has_5_uploads_max
    errors.add(:base, "cannot have more than 5 uploads") if uploads.size > 5
  end

  def user_can_map
    errors.add(:base, "user cannot add maps for this project") unless authorable.is_a?(User) and project.mappable_by?(authorable)
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

#==========
#= FILTERS
#========

  before_filter :authenticate_user!, :except => [:show, :index]

#============
#= RESOURCES
#==========

  inherit_resources
  belongs_to :project, :optional => true, :finder => :find_by_slug!
  load_and_authorize_resource :project
  load_and_authorize_resource :map, :through => :project

#===============
#= CRUD ACTIONS
#=============

  def show
    build_breadcrumbs
  end

  def new
    build_breadcrumbs
    add_breadcrumb "New", new_project_map_path(@project)
  end

  def edit
    build_breadcrumbs
    add_breadcrumb "Edit", edit_project_map_path(@project)
  end

  def create
    @map.authorable = current_user unless (params[:map][:authorable_id].present? and admin?)
    @map.lump = @project.game.default_lumpname unless (params[:map][:lump].present?)

    respond_to do |format|
      if @map.save
        format.html { redirect_to [@project, @map], :notice => 'Map was successfully created.' }
        format.json { render :json => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.json { render :json => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

#==========
#= METHODS
#========

  protected

  def build_breadcrumbs
    add_breadcrumb "Projects", :projects_path
    add_breadcrumb @project.name, project_path(@project)
    add_breadcrumb "Maps", project_path(@project, :anchor => 'maps')
    add_breadcrumb @map.name, project_map_path(@project, @map) if @map and !@map.new_record?
  end

end

app/views/maps/_form.html.haml
.form-600-border
  %h2= form_title
  = simple_form_for([@project, @map]) do |f|
    -if notice
      .notice-div
        = notice
        = link_to "Back to maps list.", project_maps_path(@project)
    = f.error_notification

    .form-inputs
      = f.input :name
      = f.input :lump, :placeholder => @project.game.default_lumpname
      = f.input :desc
      .centered-actions
        = f.button :submit

app/views/maps/_map.haml
.row
  .six.columns
    %h4= map.name
    = mkd map.desc
  .six.columns.resource-actions
    - if @project.mappable_by?(current_user)
      = link_to 'New Resource', new_project_map_resource_path(@project, map), :class => 'small white nice button radius'
    - if @project.mappable_by?(current_user)
      = link_to 'New Image', new_project_map_map_image_path(@project, map), :class => 'small white nice button radius'
    - if can? :update, map
      = link_to 'Edit', edit_project_map_path(@project, map), :class => 'small white nice button radius'
    - if can? :destroy, map
      = link_to 'Destroy', project_map_path(@project, map), :confirm => 'Are you sure?', :method => :delete, :class => 'small white nice button radius alert'

app/views/maps/edit.html.haml
.twelve.columns
  .row
    .eight.columns.centered.c222.black-border
      = render 'form', :form_title => "Editing `#{@map.name}` in `#{@project.name}`"

app/views/maps/index.html.haml
%div{ :data => { :project_slug => @project.slug } }

%h1 Listing maps

-if can? :create, Map
  .form-links
    = link_to 'New Map', new_project_map_path

%table
  %tr
    %th Name
    %th
    %th
    %th
    %th

  - @maps.each do |map|
    %tr
      %td= map.name
      %td= link_to 'Show', project_map_path(@project, map)
      %td= link_to 'Edit', edit_project_map_path(@project, map)
      %td= link_to 'Destroy', project_map_path(@project, map), :confirm => 'Are you sure?', :method => :delete
      //%td= link_to 'Download', download_project_map_path(@project, map)

%br

-if can? :create, Map
  .form-links
    = link_to 'New Map', new_project_map_path

app/views/maps/new.html.haml
.twelve.columns
  .row
    .eight.columns.centered.c222.black-border
      = render 'form', :form_title => "New map for `#{@project.name}\`"

app/views/maps/show.html.haml
%p#notice= notice

%dl.nice.contained.tabs
  %dd= link_to 'Overwiew', '#overview', :class => 'active'
  %dd= link_to 'Resources', '#resources'
  %dd= link_to 'Screens', '#screens'

%ul.nice.contained.tabs-content
  %li.panel.c333.black-border.project-overview.active#overviewTab
    =render @map
  %li.panel.c333.black-border.files#resourcesTab
    .row
      .ten.columns
        - @map.uploads.each do |mwf|
          .row
            .three.columns
              %div
                = mwf.upload_updated_at.strftime('%c')
            .nine.columns
              %span= mwf.name
              -if mwf.downloadable_by?(current_user)
                %span (
                %span= link_to 'download', download_project_map_upload_path(@project, @map, mwf)
                %span )
      .two.columns.resource-actions
        - if @project.mappable_by? current_user
          = link_to 'New Resource', new_project_map_resource_path(@project, @map), :class => 'small white nice button radius'
  %li.panel.c333.black-border.map-screens#screensTab
    %p coming soon