config/routes.rb
Doomhub::Application.routes.draw do

  root :to => 'news#index'

  get "/p/:id/m" => redirect("/p/%{id}#maps")
  get "/p/:project_id/m/:id/f" => redirect("/p/%{project_id}/m/%{id}#files")
  get "/p/:project_id/m/:id/i" => redirect("/p/%{project_id}/m/%{id}#images")

  resources :projects, :path => '/p' do
    resources :file_links, path: '/l', except: [:index]
    resources :comments, :path => '/c', except: [:edit]
    resources :resources, :path => '/r', only: [:new, :index]
    resources :maps, :path => '/m', :except => [:index] do
      resources :uploads, :path => '/f', :except => [:index] do
        member { get :download }
      end
      resources :map_images, :path => '/i', :except => [:index] do
        member { get :auth_url }
      end
      resources :file_links, path: '/l', except: [:index]
      resources :resources, :path => '/r', only: [:new, :index]
    end
  end

  resources :news, :path => '/n'

  resources :users, :path => '/u', :only => [:show, :index] do
    resources :projects, :path => '/p'
  end

  devise_for :user, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "new",
    :registration => 'registration'
  }

end

app/models/project.rb
class Project < ActiveRecord::Base

  acts_as_paranoid

#========
#= ASSOC
#======

  belongs_to :creator, :class_name => "User", :foreign_key => "user_id"
  belongs_to :game
  belongs_to :item_access
  belongs_to :source_port

  has_many :comments, :as => :commentable
  has_many :file_links, as: :file_linkable
  has_many :item_invites, :as => :invitable
  has_many :map_images, :through => :maps
  has_many :maps, :dependent => :delete_all
  has_many :users, :through => :item_invites

#==============
#= FRIENDLY_ID
#============

  extend FriendlyId
  friendly_id :url_name, :use => [:slugged, :history]

#==============
#= VALIDATIONS
#============

  validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
  validates :url_name, :uniqueness => {:case_sensitive => false}

#============
#= CALLBACKS
#==========

  before_save :generate_default_url_name

  def generate_default_url_name
    unless self.url_name.present?
      self.url_name = name
      self.send :set_slug
    end
  end

#=========
#= SCOPES
#=======

  scope :public_view, where{public_view == true}
  scope :private_view, where{public_view == false}
  scope :public_join, where{public_join == true}
  scope :private_join, where{public_join == false}

  scope :readable_by, lambda { |user|
    (mappable_by(user) + public_view).uniq
  }

  scope :mappable_by, lambda { |user|
    return [] unless user
    return all if user.admin?
    includes(:item_invites).where{
      (user_id == user.id) |
      (public_join == true) |
      (item_invites.user_id == user.id)
    }
  }

#==========
#= METHODS
#========

  def readable_by?(user)
    return true if mappable_by? user
    return public_view
  end

  def mappable_by?(user)
    return false unless user
    return true if user.admin?
    user == creator or
    public_join or
    users.include? user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

#==========
#= FILTERS
#========

  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :build_breadcrumbs, except: [:create, :update, :destroy]

#============
#= RESOURCES
#==========

  inherit_resources
  belongs_to :user, :optional => true, :finder => :find_by_login!
  load_and_authorize_resource :user
  load_and_authorize_resource :project, :through => :user

#===============
#= CRUD ACTIONS
#=============

  def index
    @projects = Project.readable_by current_user
  end

  def show
    @maps = @project.maps
    @comments = @project.comments.page nil
    @comment = Comment.new
  end

  def new
    add_breadcrumb 'New', new_project_path
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @project }
    end
  end

  def edit
    add_breadcrumb 'Edit', edit_project_path(@project)
  end

  def create
    @project.creator = current_user
    @project.url_name = @project.name unless (params[:project][:url_name].present?)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project), :notice => 'Project was successfully created.' }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    params[:project][:url_name] = @project.name unless (params[:project][:url_name].present?)

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

#==========
#= METHODS
#========

  protected

  def build_breadcrumbs
    add_breadcrumb "Users", :users_path, :allowed => @user.superadmin? if @user
    add_breadcrumb @user.login, user_path(@user) if @user
    add_breadcrumb (@user ? "#{@user.login}'s projects" : 'Projects'), :collection_path
    add_breadcrumb @project.name, project_path(@project) if @project and !@project.new_record?
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
.form-600-border
  %h2= form_title
  = simple_form_for(@project) do |f|
    -if notice
      .notice-div
        = notice
        = link_to "Back to projects list.", projects_path
    = f.error_notification

    .form-inputs
      = f.input :name
      = f.input :url_name
      %fieldset
        %legend Accessability
        = f.input :public_view, :as => :zurb_boolean, :label => "Is the project publicly visible?"
        = f.input :public_join, :as => :zurb_boolean, :label => "Can anyone join the project?"
      = f.input :description
      = f.association :game, :include_blank => false
      = f.association :source_port, :include_blank => false
      .centered-actions
        = f.button :submit

app/views/projects/_project.haml
=render 'titlebar', :project => project, :buttons => [:edit, :new_map]
.row
  .seven.columns
    .row
      #project-game-data.c222.black-border.tall
        %div
          %span{:style => "font-weight: bold;"} Game:
          %span= project.game.name
        %div
          %span{:style => "font-weight: bold;"} Source Port:
          %span= project.source_port.name
        %div
          %span{:style => "font-weight: bold;"} Author:
          %span= project.creator.login
        %div
          %span{:style => "font-weight: bold;"} Founded:
          %span= project.created_at.strftime("%B #{project.created_at.day.ordinalize}, %Y")
  .five.columns
    .row
      #project-slideshow-container.c222.black-border.tall
        #project-slideshow
          -if project.map_images.present?
            #project-orbit
              - project.map_images.each do |mi|
                %div
                  = image_tag image_path(mi.image.expiring_url(nil, :medium))
          -else
            #project-empty-orbit
              This project has no images :(


-unless project.description.empty?
  #project-description-container.row
    #project-description.c222.black-border
      = mkd project.description

app/views/projects/_short_summary.haml
.c333.black-border.project-short-summary
  .row
    .six.column
      = link_to project.name, project
    .three.column
      = "#{project.game.name} / #{project.source_port.name}"
    .three.column
      = project.creator.login

app/views/projects/_summary.haml
.c333.black-border
  =render 'titlebar', :project => project
  .row
    .nine.columns
      .project-description-container
        .project-description.c222.black-border
          = project.description.html_safe
    .three.columns
      .row.project-summary
        .c222.project-slideshow.black-border.short
          = image_tag 'doommy.jpg', :width => 170
        .c222.project-game-data.black-border
          %span= "for #{project.source_port.name} #{project.game.name} by #{project.creator.login}"

app/views/projects/_titlebar.haml
-title = (defined?(title) ? title : project.name)
.row.project-topbar
  .eight.columns
    %h4= link_to_unless_current(title || project.name, project)
  .four.columns.resource-actions
    -if can?(:update, project) and buttons.include? :edit
      = link_to 'Edit', edit_project_path(project), :class => 'small white nice button radius'
    -if can?(:update, project) and buttons.include? :new_map
      = link_to 'New Map', new_project_map_path(project), :class => 'small white nice button radius'
    -if can?(:destroy, project) and buttons.include? :destroy
      = link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => 'small white nice button radius alert'

app/views/projects/edit.html.haml
.twelve.columns
  .row
    .eight.columns.centered.c222.black-border
      = render 'form', :form_title => "Editing \"#{@project.name}\""

app/views/projects/index.html.haml
%h2= (@user ? "My projects" : "All projects")
.c222.black-border.project-short-summary.header
  .row
    .six.column
      %h5 Project name
    .three.column
      %h5 Game / Source Port
    .three.column
      %h5 Founder
= render :partial => 'short_summary', :collection => @projects, :as => :project

app/views/projects/new.html.haml
.twelve.columns
  .row
    .eight.columns.centered.c222.black-border
      = render 'form', :form_title => "New Project"

app/views/projects/show.html.haml
%p#notice= notice

%dl.nice.contained.tabs#navbar
  %dd#overview
    = link_to 'Overview', '#overview', :class => 'active'
  %dd.paginated#comments
    = link_to 'Comments', '#comments'
    %span.page
  %dd#maps
    = link_to 'Maps', '#maps'
  %dd#images
    = link_to 'Images', '#images'
  %dd#resources
    = link_to 'Resources', '#resources'
%ul.nice.contained.tabs-content#project-show
  %li.c333.black-border.project-overview.active#overviewTab
    = render @project
  %li.c333.black-border.project-maps#commentsTab
    = render "shared/comments", :commentable => @project, :comment => @comment
  %li.c333.black-border.project-maps#mapsTab
    .row
      .nine.columns
        - @maps.each do |map|
          .row
            %span= "#{map.lump}:"
            %span= link_to map.name, [@project, map]
            -unless map.uploads.empty?
              %span (
              = link_to "uploads", project_map_path(@project, map, :anchor => 'uploads')
              %span )
      .three.columns.resource-actions
        -if @project.mappable_by? current_user
          = link_to 'New Map', new_project_map_path(@project), :class => 'small white nice button radius'
  %li.c333.black-border.project-images#imagesTab
    = render 'titlebar', :project => @project, :title => "#{@project.name} gallery", :buttons => []
    = render 'shared/image_gallery', :project => @project
  %li.c333.black-border.project-resources#resourcesTab
    -if @project.mappable_by? current_user
      = link_to 'New Resource', new_resource_path(@project), :class => 'small white nice button radius'