config/routes.rb
Doomhub::Application.routes.draw do

  root :to => 'news#index'

  get "/p/:id/m" => redirect("/p/%{id}#maps")
  get "/p/:project_id/m/:id/f" => redirect("/p/%{project_id}/m/%{id}#files")
  get "/p/:project_id/m/:id/i" => redirect("/p/%{project_id}/m/%{id}#images")

  resources :projects, :path => '/p' do
    resources :file_links, path: '/l', except: [:index]
    resources :comments, :path => '/c', except: [:edit]
    resources :resources, :path => '/r', only: [:new, :index]
    resources :maps, :path => '/m', :except => [:index] do
      resources :uploads, :path => '/f', :except => [:index] do
        member { get :download }
      end
      resources :map_images, :path => '/i', :except => [:index] do
        member { get :auth_url }
      end
      resources :file_links, path: '/l', except: [:index]
      resources :resources, :path => '/r', only: [:new, :index]
    end
  end

  resources :news, :path => '/n'

  resources :users, :path => '/u', :only => [:show, :index] do
    resources :projects, :path => '/p'
  end

  devise_for :user, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "new",
    :registration => 'registration'
  }

end

app/models/upload.rb
class Upload < ActiveRecord::Base

  acts_as_paranoid

#========
#= ASSOC
#======

  belongs_to :map
  belongs_to :authorable, polymorphic: true

  delegate :project, to: :map

#=======
#= ATTR
#=====

  # Setup accessible (or protected) attributes for your model
  attr_accessible :archive, :name

#============
#= PAPERCLIP
#==========
  ALLOWED_MIMES = ["application/zip", "application/x-7z-compressed", "application/x-rar-compressed"]

  has_attached_file :archive,
                    :keep_old_files => true,
                    :url => ":path",
                    :path => Settings.paperclip.project.map.archive.storage_path

  Paperclip.interpolates :project_id do |attachment, style|
    attachment.instance.project.id
  end

  Paperclip.interpolates :map_id do |attachment, style|
    attachment.instance.map.id
  end

  Paperclip.interpolates :name do |attachment, style|
    attachment.instance.name.parameterize
  end

#==============
#= VALIDATIONS
#============

  validate :name, :presence => true
  validate :check_attachment
  validate :check_if_can_add_to_map

  def check_attachment
    if (MIME::Types.type_for(archive_file_name).map(&:to_s) & ALLOWED_MIMES).empty?
      errors[:archive] << "File must be a valid zip / rar / 7z achive"
    end
    if archive.size > 1.megabyte
      errors[:archive] << "File must not be over 1 MB"
    end
  end

  def check_if_can_add_to_map
    errors[:map] << 'Cannot add more than 5 uploads per map' \
      if map.uploads.count >= 5
  end

#==========
#= METHODS
#========

  def downloadable_by?(user)
    project.mappable_by?(user)
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

#==========
#= FILTERS
#========

  before_filter :authenticate_user!, :except => [:show, :index, :download]

#============
#= RESOURCES
#==========

  inherit_resources
  belongs_to :project, :optional => true, :finder => :find_by_slug!
  belongs_to :map, :optional => true, :finder => :find_by_slug!
  load_and_authorize_resource :project
  load_and_authorize_resource :map, :through => :project
  load_and_authorize_resource :upload, :through => :map

#===============
#= CRUD ACTIONS
#=============

  def new
    build_breadcrumbs
  end

  def create
    params[:upload][:name] ||= @map.slug
    @upload = @map.uploads.build(params[:upload])
    @upload.authorable = current_user unless (params[:upload][:authorable_id].present? and admin?)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to [@project, @map], :notice => 'Upload was successfully added.' }
        format.json { render :json => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.json { render :json => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @upload.destroy
        format.html { redirect_to [@project, @map], :notice => 'Upload was successfully destroyed.' }
        format.json { render :json => @map, :location => @map }
      else
        format.html { redirect_to [@project, @map], :error => 'Upload was NOT destroyed.' }
        format.json { render :status => :unprocessable_entity }
      end
    end
  end

#================
#= OTHER ACTIONS
#==============

  def download
    if Rails.env.production?
      redirect_to @upload.archive.expiring_url(10)
    else
      redirect_to @upload.archive.url
    end
  end

#==========
#= METHODS
#========

  protected

  def build_breadcrumbs
    add_breadcrumb "Projects", :projects_path
    add_breadcrumb @project.name, project_path(@project)
    add_breadcrumb "Maps", project_path(@project, :anchor => 'maps')
    add_breadcrumb @map.name, project_map_path(@project, @map)
    add_breadcrumb "Map Uploads", project_map_path(@project, @map, :anchor => 'uploads')
  end

end

app/views/uploads/_form.html.haml
= simple_form_for([@project, @map, @upload]) do |f|
  = f.error_notification

  = f.input :name, :placeholder => @map.slug
  = f.input :upload
  .centered-actions
    = f.button :submit

app/views/uploads/index.html.haml
%h1 Listing maps

%table
  %tr
    %th Name
    %th
    %th
    %th
    %th

  - @maps.each do |map|
    %tr
      %td= map.name
      %td= link_to 'Show', project_map_path(@project, map)
      %td= link_to 'Edit', edit_project_map_path(@project, map)
      %td= link_to 'Destroy', project_map_path(@project, map), :confirm => 'Are you sure?', :method => :delete
      //%td= link_to 'Download', download_project_map_path(@project, map)

%br

-if can? :create, Map
  .form-links
    = link_to 'New Map', new_project_map_path

app/views/uploads/new.haml
.twelve.columns
  .row
    .eight.columns.centered.c222.black-border
      .c222
        %h5= "Adding a new archive for `#{@map.name}`, keep in mind:"
        %ul
          %li Only Zip and 7z archives are allowed
          %li The maximum size of an archive is 1 MB
          %li You can add up to 5 archives per map.
      .form-border
        %h2 New Upload
        = render 'form'

app/views/uploads/show.html.haml
%p
  %b Name:
  = @map.name

.form-links
  = link_to 'Edit', edit_project_map_path(@project)
  \|
  = link_to 'Back', project_maps_path